Demo.PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Demo.BAL.Interfaces;
using Demo.DAl.Entities;
using NToastNotify;

namespace Demo.PL.Controllers;

public class DepartmentController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    // private readonly IDepartmentRepository _department;
    private readonly ILogger<DepartmentController> logger;
    private readonly IToastNotification toast;

    public DepartmentController(IUnitOfWork unitOfWork,ILogger<DepartmentController> logger, IToastNotification toast)
    {
        
        _unitOfWork = unitOfWork;
        this.logger = logger;
        this.toast = toast;
    }
    public IActionResult Index()
    {
        var departments = _unitOfWork.departmentRepository.GetAll();
        return View(departments);
    }

    [HttpGet]
    public IActionResult Create()
    {

        return View(new Department());
    }
    [HttpPost]
    public IActionResult Create(Department department)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.departmentRepository.Add(department);
            _unitOfWork.commit();
            toast.AddSuccessToastMessage(" Department Created Successfully");
            return RedirectToAction(nameof(Index));

        }
        else
            return View(department);

    }

    public IActionResult Details(int? id)
    {
        try
        {
            if (id == null)
            {
                return BadRequest();
            }
            var department = _unitOfWork.departmentRepository.GetById(id);

            if (department == null)
            {
                return NotFound();
            }
            return View(department);

        }
        catch (Exception ex)
        {
            logger.LogError(ex.Message);
            return RedirectToAction("Error", "Home");

        }
        
        
        
    }
    [HttpGet]
    public IActionResult Edit(int? id)
    {
        try
        {
            if (id == null)
            {
                return BadRequest();
            }
            var department = _unitOfWork.departmentRepository.GetById(id);

            if (department == null)
            {
                return NotFound();
            }
            return View(department);

        }
        catch (Exception ex)
        {
            logger.LogError(ex.Message);
            return RedirectToAction("Error", "Home");

        }



    }
  
    public IActionResult Edit(Department department)
    {
        if(ModelState.IsValid)
        {
            _unitOfWork.departmentRepository.Update(department);
            _unitOfWork.commit();
            toast.AddSuccessToastMessage(" Department updated Successfully");


            return RedirectToAction(nameof(Index));
        }
        else
            return View(department);


    }
    [HttpGet]
    public IActionResult Delete(int? id)
    {
        try
        {
            if (id == null)
            {
                return BadRequest();
            }
            var department = _unitOfWork.departmentRepository.GetById(id);

            if (department == null)
            {
                return NotFound();
            }
            return View(department);

        }
        catch (Exception ex)
        {
            logger.LogError(ex.Message);
            return RedirectToAction("Error", "Home");

        }



    }
    [HttpPost]
    public IActionResult Delete(Department department)
    {
        _unitOfWork.departmentRepository.Delete(department);
        _unitOfWork.commit();
        toast.AddWarningToastMessage(" Department Deleted");

        return RedirectToAction(nameof(Index));
    }

}

Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BAL.Interfaces;
using Demo.DAl.Entities;
using Demo.PL.Helper;
using Demo.PL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using NToastNotify;
using System.Reflection.Metadata;

namespace Demo.PL.Controllers
{
    public class EmployeeController : Controller
    {
        
        private readonly IUnitOfWork _unitOfWork;
        private readonly IToastNotification toastNotification;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork,IToastNotification toastNotification,IMapper mapper)
        {
           
            _unitOfWork = unitOfWork;
            this.toastNotification = toastNotification;
            _mapper = mapper;
        }
        public IActionResult Index( string SearchValue="")
        {
            IEnumerable<Employee> employees;
            IEnumerable<EmployeeViewModel> employeeViews;


            if (string.IsNullOrEmpty(SearchValue))
                employees = _unitOfWork.employeeRepository.GetAll();
               
            else
                employees = _unitOfWork.employeeRepository.Search(SearchValue);

              employeeViews = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);

            return View(employeeViews);
        }

        
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Not Found");
            }
            else
            {
                 var employee = _unitOfWork.employeeRepository.GetEagerLoadingById(id);
                if(employee == null)
                {
                    return NotFound();
                }
                 var empView=_mapper.Map<EmployeeViewModel>(employee);
              return View(empView);
            }
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.departmets=_unitOfWork.departmentRepository.GetAll();
            return View( new EmployeeViewModel() ) ;

        }


        [HttpPost]
        public IActionResult Create(EmployeeViewModel employeeViewModel)
        {
          //  ModelState["Department"].ValidationState=ModelValidationState.Valid;
            if (ModelState.IsValid)
            {
                //Manual Map Dto

                //Employee emp = new Employee
                //{
                //    Name= employee.Name,
                //    Address= employee.Address,
                //    DepartmentId= employee.DepartmentId,
                //    Email = employee.Email,
                //    Salary = employee.Salary,
                //    HiringDate = employee.HiringDate,
                //    IsActive= employee.IsActive
                //};

                //Auto Mapper
                var emp =_mapper.Map<Employee>(employeeViewModel);
                emp.ImageUrl = DocumnetSetting.UploadFile(employeeViewModel.File, "Images");
                _unitOfWork.employeeRepository.Add(emp);
                _unitOfWork.commit();
                toastNotification.AddSuccessToastMessage("Added Sucessfully");
                return RedirectToAction("Index");
                
            }
            ViewBag.departmets = _unitOfWork.departmentRepository.GetAll();
            return View(employeeViewModel);

        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.departmets = _unitOfWork.departmentRepository.GetAll();
            try
            {
                if (id == null)
                {
                    return BadRequest();
                }
                var employee = _unitOfWork.employeeRepository.GetById(id);

                if (employee == null)
                {
                    return NotFound();
                }
                var empView=_mapper.Map<EmployeeViewModel>(employee);    
                return View(empView);

            }
            catch (Exception ex)
            {
               
                return RedirectToAction("Error", "Home");

            }



        }
        [HttpPost]
        public IActionResult Edit(EmployeeViewModel employeeView)
        {
            //ModelState["Department"].ValidationState = ModelValidationState.Valid;
            if (ModelState.IsValid)
            {

                var employee = _mapper.Map<Employee>(employeeView);
                employee.ImageUrl = DocumnetSetting.UploadFile(employeeView.File, "Images");


                _unitOfWork.employeeRepository.Update(employee);
                _unitOfWork.commit();
                toastNotification.AddSuccessToastMessage("Updated Sucessfully");

                return RedirectToAction(nameof(Index));
            }
            else
           ViewBag.departmets = _unitOfWork.departmentRepository.GetAll();
            return View(employeeView);


        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {


            if (id == null)
            {
                return BadRequest();
            }
            var employee = _unitOfWork.employeeRepository.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            _unitOfWork.employeeRepository.Delete(employee); 

            _unitOfWork.commit();
            toastNotification.AddWarningToastMessage("Data Was Deleted");



            return RedirectToAction(nameof(Index));

        }
      
    }
}

Demo.PL/Controllers/RolesController.cs
using Demo.DAl.Entities;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Patterns;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RolesController(RoleManager<ApplicationRole> roleManager,UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            
          var roles= await _roleManager.Roles.ToListAsync();
           return View(roles);
        }
        public async Task<IActionResult> Create()
        {

            return View( new ApplicationRole()  );
        }
        [HttpPost]
        public async Task<IActionResult> Create( ApplicationRole applicationRole)
        {
            if(ModelState.IsValid)
            {
               var result= await _roleManager.CreateAsync(applicationRole);
               
                if(result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return View(new ApplicationRole());
        }


        public async Task<IActionResult> Delete(string id)
        {
                var role= await _roleManager.FindByIdAsync(id);
                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddOrRemoveRoleToUser(string id)
        {
            if (id == null)
                return NotFound();
            var role=await _roleManager.FindByIdAsync(id);
            if(role == null)
                return NotFound();
          //  ViewBag.roleId = id;
            var users= await _userManager.Users.ToListAsync();
            List<UserInRoleViewModel> RolesViewUsers =new List<UserInRoleViewModel>();    
            foreach(var user in users)
            {
                UserInRoleViewModel usersInRoleViews = new UserInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };
                if ( await _userManager.IsInRoleAsync(user,role.Name))
                    usersInRoleViews.IsSelected=true;
                else
                    usersInRoleViews.IsSelected=false;

               RolesViewUsers.Add(usersInRoleViews);
               
            }
            return View(RolesViewUsers);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveRoleToUser(string id, List<UserInRoleViewModel> userInRoleViewModel)
        {
            if (id == null)
                return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                foreach(var user in userInRoleViewModel)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if(appUser != null)
                    {
                        if (user.IsSelected && !(await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        else if(!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                             await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                    }
                    
                }

               return RedirectToAction(nameof(Index));
            }
            return View(userInRoleViewModel);
        }

    }
}

Demo.PL/Controllers/UsersController.cs
using Demo.DAl.Context;
using Demo.DAl.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using NToastNotify;
using NuGet.Versioning;
using System.Reflection.Metadata.Ecma335;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IToastNotification _toastNotification;

        public UsersController(UserManager<ApplicationUser> userManager,IToastNotification toastNotification)
        {
             _userManager = userManager;
             _toastNotification = toastNotification;
        }
        public async Task<IActionResult>  Index(string SearchValue= "")
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(SearchValue))
            {
                users = await _userManager.Users.ToListAsync();
            }
            else
            {
                users = await _userManager.Users.Where(user => user.Email.Trim().ToLower().Contains(SearchValue.Trim().ToLower())).ToListAsync();
            }
            return View(users);
        }

        public async Task<IActionResult> Details(string Id,string ActionName ="Details")
        {
            if (Id is  null)
                return NotFound();
            var user= await _userManager.Users.FirstOrDefaultAsync(user => user.Id == Id);
            if(user == null) return NotFound();

			return View(ActionName, user);
		}
		[HttpGet]
		public async Task<IActionResult> Edit(string Id)
		{
            return await Details(Id, "Edit");

		}

		[HttpPost]
		public async Task<IActionResult> Edit(string Id, ApplicationUser applicationUser)
		{
            if (applicationUser.Id != Id)
                return NotFound();
            if (ModelState.IsValid) { 
            var user = _userManager.Users.FirstOrDefault(user => user.Id == Id);

            user.UserName= applicationUser.UserName;
            user.NormalizedUserName= applicationUser.UserName.ToUpper();

            var result= await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    _toastNotification.AddInfoToastMessage("User Was Updated");

                    return RedirectToAction(nameof(Index));
                }
                    
                foreach (var item in result.Errors)
                    ModelState.AddModelError("",item.Description);
           }
            return View(applicationUser);
		}


        
        public async Task<IActionResult> Delete(string Id)
        {
           
            
           var user = _userManager.Users.FirstOrDefault(user => user.Id == Id);
                if(user == null) return NotFound();


            var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
            {
                _toastNotification.AddSuccessToastMessage("User Was Deleted");
                return RedirectToAction(nameof(Index));

            }
                    
                foreach (var item in result.Errors)
                    ModelState.AddModelError("", item.Description);

            return RedirectToAction(nameof(Index));
        }
    }
}

Demo.PL/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/Style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	
	<!-- //main -->
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
	@await Component.InvokeAsync("NToastNotify")
</body>
</html>

Demo.PL/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManger
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Manege Employee</a>
                        </li>
                        @if(SignInManger.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark " asp-area="" asp-controller="Roles" asp-action="Index"> Roles</a>
                            </li>
                        }
                    </ul>
                    @if (SignInManger.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut"> Sign Out</a>
                            </li>

                        </ul>

                       
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>